name: Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        type: choice
        options:
          - snapshots
          - releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Publish Snapshots
        if: github.event.inputs.repo == 'snapshots'
        run: ./gradlew publishAllPublicationsToSonatypeOssSnapshotsRepository
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Publish Releases
        if: github.event.inputs.repo == 'releases'
        run: ./gradlew publishAllPublicationsToSonatypeOssReleasesRepository
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
