name: Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Hello World.
